// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkL97giZawPNhSnl8oKJiSIzS7_pgnkZA',
    appId: '1:1023563808684:web:9966b5c366fcbad03b4409',
    messagingSenderId: '1023563808684',
    projectId: 'drastroapp',
    authDomain: 'drastroapp.firebaseapp.com',
    storageBucket: 'drastroapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkL97giZawPNhSnl8oKJiSIzS7_pgnkZA',
    appId: '1:1023563808684:android:flutter_dr_astro',
    messagingSenderId: '1023563808684',
    projectId: 'drastroapp',
    storageBucket: 'drastroapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkL97giZawPNhSnl8oKJiSIzS7_pgnkZA',
    appId: '1:1023563808684:ios:flutter_dr_astro',
    messagingSenderId: '1023563808684',
    projectId: 'drastroapp',
    storageBucket: 'drastroapp.firebasestorage.app',
    iosBundleId: 'com.drastro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkL97giZawPNhSnl8oKJiSIzS7_pgnkZA',
    appId: '1:1023563808684:ios:flutter_dr_astro',
    messagingSenderId: '1023563808684',
    projectId: 'drastroapp',
    storageBucket: 'drastroapp.firebasestorage.app',
    iosBundleId: 'com.drastro.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkL97giZawPNhSnl8oKJiSIzS7_pgnkZA',
    appId: '1:1023563808684:web:9966b5c366fcbad03b4409',
    messagingSenderId: '1023563808684',
    projectId: 'drastroapp',
    authDomain: 'drastroapp.firebaseapp.com',
    storageBucket: 'drastroapp.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDkL97giZawPNhSnl8oKJiSIzS7_pgnkZA',
    appId: '1:1023563808684:web:9966b5c366fcbad03b4409',
    messagingSenderId: '1023563808684',
    projectId: 'drastroapp',
    authDomain: 'drastroapp.firebaseapp.com',
    storageBucket: 'drastroapp.firebasestorage.app',
  );
}
